### ISSUE TITLE
DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by adrianbartnik** [glic3rinu/passlib#56]
Hey everyone, I am not sure if this library is maintained anymore (last commit was in 2015), but when using this library with python 3.11, the following warning is printed:

```
.venv/lib/python3.11/site-packages/passlib/utils/__init__.py:854
  .../.venv/lib/python3.11/site-packages/passlib/utils/__init__.py:854: DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13
    from crypt import crypt as _crypt
```

Since there is not evening a planned release date for python 3.12, there is still time to fix this.

**Comment by domrim** [comment]
this is not the official repo anymore. see https://passlib.readthedocs.io/en/stable/. The code is now hosted at https://foss.heptapod.net/python-libs/passlib
